[[mods]]
nombre = "3dSkinLayers-forge-1.1.0"
version = ""

[[mods]]
nombre = "abnormals_core-1.16.5-3.3.1"
version = ""

[[mods]]
nombre = "AI-Improvements-1.16.5-0.5.0"
version = ""

[[mods]]
nombre = "alexsmobs-1.12.1"
version = ""

[[mods]]
nombre = "Aquaculture-1.16.5-2.1.23"
version = ""

[[mods]]
nombre = "aquamirae-5.4.API11"
version = ""

[[mods]]
nombre = "architectury-1.32.68"
version = ""

[[mods]]
nombre = "ars_nouveau-1.16.5-1.25.10"
version = ""

[[mods]]
nombre = "betteranimalsplus-1.16.5-11.0.10-forge"
version = ""

[[mods]]
nombre = "BetterAnimationsCollection-v1.2.4-1.16.5-Forge"
version = ""

[[mods]]
nombre = "BetterCaves-Forge-1.16.4-1.1.2"
version = ""

[[mods]]
nombre = "betterfpsdist-1.2"
version = ""

[[mods]]
nombre = "BetterMineshafts-Forge-1.16.4-2.0.4"
version = ""

[[mods]]
nombre = "BetterModsButton-v1.0.5-1.16.5-Forge"
version = ""

[[mods]]
nombre = "BetterStrongholds-1.16.4-1.2.1"
version = ""

[[mods]]
nombre = "BetterThirdPerson-Forge-1.16.4-1.9.0"
version = ""

[[mods]]
nombre = "BiomesOPlenty-1.16.5-13.1.0.477-universal"
version = ""

[[mods]]
nombre = "byg-1.3.6"
version = ""

[[mods]]
nombre = "cfm-7.0.0pre22-1.16.3"
version = ""

[[mods]]
nombre = "cherishedworlds-forge-1.16.5-5.1.1.0"
version = ""

[[mods]]
nombre = "Chunky-1.2.123"
version = ""

[[mods]]
nombre = "citadel-1.8.1-1.16.5"
version = ""

[[mods]]
nombre = "cloth-config-4.17.101-forge"
version = ""

[[mods]]
nombre = "Clumps-6.0.0.28"
version = ""

[[mods]]
nombre = "collective-1.16.5-5.49"
version = ""

[[mods]]
nombre = "ColtCosmeticArmorMod-1.2.5"
version = ""

[[mods]]
nombre = "combatroll-1.0.8.2+1.16"
version = ""

[[mods]]
nombre = "ConfigMenusForge-v1.2.0-1.16.5-Forge"
version = ""

[[mods]]
nombre = "constructsarmory-forge-2.0.0-alpha.2+1.16.5"
version = ""

[[mods]]
nombre = "Controlling-7.0.0.29"
version = ""

[[mods]]
nombre = "CosmeticArmorReworked-1.16.5-v5"
version = ""

[[mods]]
nombre = "CraftTweaker-1.16.5-7.1.2.525"
version = ""

[[mods]]
nombre = "create-addon-v5"
version = ""

[[mods]]
nombre = "create-confectionery1.16.5_v1.0.2"
version = ""

[[mods]]
nombre = "create-mc1.16.5_v0.3.2g"
version = ""

[[mods]]
nombre = "create-stuff-additions1.16.5_v1.1.6"
version = ""

[[mods]]
nombre = "createaddition-1.16.5-20220129a"
version = ""

[[mods]]
nombre = "CreateArmorAndWeaponsv2"
version = ""

[[mods]]
nombre = "createautomated-1.16.5-1.4.1a"
version = ""

[[mods]]
nombre = "createcafe-1.16.5-2.4"
version = ""

[[mods]]
nombre = "createdeco-1.1.2-1.16.5"
version = ""

[[mods]]
nombre = "CreateDecoCasing"
version = ""

[[mods]]
nombre = "CreateDrinks-1.0.1-1.16.5"
version = ""

[[mods]]
nombre = "creategears-1.16.5-1.3.3"
version = ""

[[mods]]
nombre = "create_recycle_0.9.0_forge_1.16.5"
version = ""

[[mods]]
nombre = "CreativeCore_v2.2.1_mc1.16.5"
version = ""

[[mods]]
nombre = "curios-forge-1.16.5-4.1.0.0"
version = ""

[[mods]]
nombre = "DungeonCrawl-1.16.5-2.3.12"
version = ""

[[mods]]
nombre = "DungeonsArise-1.16.5-2.1.49-beta"
version = ""

[[mods]]
nombre = "DynamicTrees-1.16.5-0.10.5"
version = ""

[[mods]]
nombre = "DynamicTreesBOP-1.16.5-2.0.9"
version = ""

[[mods]]
nombre = "DynamicTreesTConstruct-1.16.5-1.3.0"
version = ""

[[mods]]
nombre = "embeddium-0.2.4+mc1.16.5"
version = ""

[[mods]]
nombre = "embeddium-extras-mc1.16.5_v1.10.4"
version = ""

[[mods]]
nombre = "embeddiumextension-1.16.5-0.0.6"
version = ""

[[mods]]
nombre = "EnchantingInfuser-v1.0.2-1.16.5-Forge"
version = ""

[[mods]]
nombre = "entitycollisionfpsfix-1.16-1.0.1"
version = ""

[[mods]]
nombre = "EntityCulling-1.16.5-2.1.7"
version = ""

[[mods]]
nombre = "fancymenu_forge_2.14.9_MC_1.16.2-1.16.5"
version = ""

[[mods]]
nombre = "FarmersDelight-1.16.5-0.6.0"
version = ""

[[mods]]
nombre = "FasterLadderClimbing-1.16.4-0.2.1"
version = ""

[[mods]]
nombre = "FastLeafDecay-v25.2"
version = ""

[[mods]]
nombre = "FastSuite-1.16.4-1.1.1"
version = ""

[[mods]]
nombre = "ferritecore-2.1.1-forge"
version = ""

[[mods]]
nombre = "flywheel-1.16-0.2.5"
version = ""

[[mods]]
nombre = "forgedfabric-0.0.7+1.16"
version = ""

[[mods]]
nombre = "FpsReducer-forge-1.24-mc1.16.5"
version = ""

[[mods]]
nombre = "geckolib-forge-1.16.5-3.0.106"
version = ""

[[mods]]
nombre = "getittogetherdrops-1.16.5-v1.2"
version = ""

[[mods]]
nombre = "goblintraders-1.7.3-1.16.5"
version = ""

[[mods]]
nombre = "GokiStats-1.16.5-1.3.2"
version = ""

[[mods]]
nombre = "gravestone-1.16.5-1.0.6"
version = ""

[[mods]]
nombre = "HardcoreRevival_1.16.5-5.2.1"
version = ""

[[mods]]
nombre = "iceandfire-2.1.12-1.16.5-patch-1"
version = ""

[[mods]]
nombre = "immersive-armors-1.5.1+1.16.5-forge"
version = ""

[[mods]]
nombre = "immersive_aircraft-0.5.2+1.16.5-forge"
version = ""

[[mods]]
nombre = "ImprovedBackpacks-1.6.2.1"
version = ""

[[mods]]
nombre = "inventorysorter-1.16.1-18.1.0"
version = ""

[[mods]]
nombre = "Jade-1.16.4-2.8.3"
version = ""

[[mods]]
nombre = "JEITweaker-1.16.5-1.1.0.49"
version = ""

[[mods]]
nombre = "konkrete_forge_1.6.1_MC_1.16.2-1.16.5"
version = ""

[[mods]]
nombre = "kotlinforforge-1.17.0-obf"
version = ""

[[mods]]
nombre = "kryptonreforged-mc1.16.5_v1.0.0"
version = ""

[[mods]]
nombre = "Ksyxis-Forge1.14thru1.16-1.1"
version = ""

[[mods]]
nombre = "kubejs-create-1605.1.4-build.12"
version = ""

[[mods]]
nombre = "kubejs-forge-1605.3.19-build.299"
version = ""

[[mods]]
nombre = "lazydfu-0.1.3"
version = ""

[[mods]]
nombre = "litematica-forge-1.16.5-0.0.0-dev.20210917"
version = ""

[[mods]]
nombre = "majrusz-library-1.16.4-2.0.1"
version = ""

[[mods]]
nombre = "majruszs-difficulty-1.16.4-1.1.0"
version = ""

[[mods]]
nombre = "malilib-forge-1.16.5-0.10.0-dev.21+beta.1"
version = ""

[[mods]]
nombre = "Mantle-1.16.5-1.6.157"
version = ""

[[mods]]
nombre = "mcw-furniture-3.2.0-mc1.16.5forge"
version = ""

[[mods]]
nombre = "minecraft-comes-alive-7.3.23+1.16.5-universal"
version = ""

[[mods]]
nombre = "mobifier-1.1.4"
version = ""

[[mods]]
nombre = "morecfm-1.3.1-1.16.3"
version = ""

[[mods]]
nombre = "morecreatestuffs-mc1.16-1.4.1b"
version = ""

[[mods]]
nombre = "Morpheus-1.16.5-4.2.70"
version = ""

[[mods]]
nombre = "mowziesmobs-1.5.27"
version = ""

[[mods]]
nombre = "MutantBeasts-1.16.4-1.1.3"
version = ""

[[mods]]
nombre = "obscure_api-11"
version = ""

[[mods]]
nombre = "occultism-1.16.5-1.29.1"
version = ""

[[mods]]
nombre = "out_of_sight-1.16.4-1.0.1"
version = ""

[[mods]]
nombre = "overworld_two-1.1-1.16.5"
version = ""

[[mods]]
nombre = "passiveshield_1.16.5-2.6"
version = ""

[[mods]]
nombre = "Patchouli-1.16.4-53.3"
version = ""

[[mods]]
nombre = "Placebo-1.16.5-4.7.1"
version = ""

[[mods]]
nombre = "player-animation-lib-forge-0.3.5+1.16.5"
version = ""

[[mods]]
nombre = "PuzzlesLib-v1.0.15-1.16.5-Forge"
version = ""

[[mods]]
nombre = "reap-1.16.5-1.0.1"
version = ""

[[mods]]
nombre = "rhino-forge-1605.1.5-build.75"
version = ""

[[mods]]
nombre = "RoadRunner-mc1.16.5-1.4.1"
version = ""

[[mods]]
nombre = "RoughlyEnoughItems-6.5.436"
version = ""

[[mods]]
nombre = "shutupexperimentalsettings-1.0.3"
version = ""

[[mods]]
nombre = "smoothboot-forge-1.16.4-1.2.2"
version = ""

[[mods]]
nombre = "spark-1.9.1-forge"
version = ""

[[mods]]
nombre = "SpawnerFix-1.16.2-1.0.0.2"
version = ""

[[mods]]
nombre = "spoornextras-1.0"
version = ""

[[mods]]
nombre = "starlight-1.2"
version = ""

[[mods]]
nombre = "strawgolem-1.16-1.9"
version = ""

[[mods]]
nombre = "TConstruct-1.16.5-3.3.4.335"
version = ""

[[mods]]
nombre = "TerraForged-1.16.5-0.2.16"
version = ""

[[mods]]
nombre = "theurgy-1.16.5-1.0.8"
version = ""

[[mods]]
nombre = "TrashSlot_1.16.3-12.2.1"
version = ""

[[mods]]
nombre = "twilightforest"
version = ""

[[mods]]
nombre = "upgrade_aquatic-1.16.5-3.1.2"
version = ""

[[mods]]
nombre = "useless-sword-1.16.5-V1.3.7"
version = ""

[[mods]]
nombre = "voicechat-forge-1.16.5-2.4.27"
version = ""

[[mods]]
nombre = "Xaeros_Minimap_FP23.8.2_Forge_1.16.5"
version = ""

[[mods]]
nombre = "xlpackets-1.16.4-1.2"
version = ""

[[mods]]
nombre = "YungsApi-1.16.4-Forge-13"
version = ""

[[mods]]
nombre = "YungsBridges-Forge-1.16.4-1.0.1"
version = ""

[[mods]]
nombre = "YungsExtras-Forge-1.16.4-1.0"
version = ""

[[mods]]
nombre = "[1.16.5]SecurityCraftv1.9.8"
version = ""

[[mods]]
nombre = "[1.16.5][Forge]RPG-HUD-3.9.1"
version = ""

