name = "DinastyCraft"
version = "v1.2"
description = ""
[[modlist]]
name = "3dSkinLayers-forge-1.1.0"
version = ".jar"

[[modlist]]
name = "abnormals_core-1.16.5-3.3.1"
version = ".jar"

[[modlist]]
name = "AI-Improvements-1.16.5-0.5.0"
version = ".jar"

[[modlist]]
name = "alexsmobs-1.12.1"
version = ".jar"

[[modlist]]
name = "Aquaculture-1.16.5-2.1.23"
version = ".jar"

[[modlist]]
name = "aquamirae-5.4.API11"
version = ".jar"

[[modlist]]
name = "architectury-1.32.68"
version = ".jar"

[[modlist]]
name = "ars_nouveau-1.16.5-1.25.10"
version = ".jar"

[[modlist]]
name = "betteranimalsplus-1.16.5-11.0.10-forge"
version = ".jar"

[[modlist]]
name = "BetterAnimationsCollection-v1.2.4-1.16.5-Forge"
version = ".jar"

[[modlist]]
name = "BetterCaves-Forge-1.16.4-1.1.2"
version = ".jar"

[[modlist]]
name = "bettercombat-1.4.5.3+1.16"
version = ".jar"

[[modlist]]
name = "betterfpsdist-1.2"
version = ".jar"

[[modlist]]
name = "BetterMineshafts-Forge-1.16.4-2.0.4"
version = ".jar"

[[modlist]]
name = "BetterModsButton-v1.0.5-1.16.5-Forge"
version = ".jar"

[[modlist]]
name = "BetterStrongholds-1.16.4-1.2.1"
version = ".jar"

[[modlist]]
name = "BetterThirdPerson-Forge-1.16.4-1.9.0"
version = ".jar"

[[modlist]]
name = "BiomesOPlenty-1.16.5-13.1.0.477-universal"
version = ".jar"

[[modlist]]
name = "byg-1.3.6"
version = ".jar"

[[modlist]]
name = "cfm-7.0.0pre22-1.16.3"
version = ".jar"

[[modlist]]
name = "cherishedworlds-forge-1.16.5-5.1.1.0"
version = ".jar"

[[modlist]]
name = "citadel-1.8.1-1.16.5"
version = ".jar"

[[modlist]]
name = "cloth-config-4.17.101-forge"
version = ".jar"

[[modlist]]
name = "Clumps-6.0.0.28"
version = ".jar"

[[modlist]]
name = "collective-1.16.5-5.49"
version = ".jar"

[[modlist]]
name = "ColtCosmeticArmorMod-1.2.5"
version = ".jar"

[[modlist]]
name = "combatroll-1.0.8.2+1.16"
version = ".jar"

[[modlist]]
name = "ConfigMenusForge-v1.2.0-1.16.5-Forge"
version = ".jar"

[[modlist]]
name = "constructsarmory-forge-2.0.0-alpha.2+1.16.5"
version = ".jar"

[[modlist]]
name = "Controlling-7.0.0.29"
version = ".jar"

[[modlist]]
name = "CosmeticArmorReworked-1.16.5-v5"
version = ".jar"

[[modlist]]
name = "CraftTweaker-1.16.5-7.1.2.525"
version = ".jar"

[[modlist]]
name = "create-addon-v5"
version = ".jar"

[[modlist]]
name = "create-confectionery1.16.5_v1.0.2"
version = ".jar"

[[modlist]]
name = "create-mc1.16.5_v0.3.2g"
version = ".jar"

[[modlist]]
name = "create-stuff-additions1.16.5_v1.1.6"
version = ".jar"

[[modlist]]
name = "createaddition-1.16.5-20220129a"
version = ".jar"

[[modlist]]
name = "CreateArmorAndWeaponsv2"
version = ".jar"

[[modlist]]
name = "createautomated-1.16.5-1.4.1a"
version = ".jar"

[[modlist]]
name = "createcafe-1.16.5-2.4"
version = ".jar"

[[modlist]]
name = "createdeco-1.1.2-1.16.5"
version = ".jar"

[[modlist]]
name = "CreateDecoCasing"
version = ".jar"

[[modlist]]
name = "CreateDrinks-1.0.1-1.16.5"
version = ".jar"

[[modlist]]
name = "creategears-1.16.5-1.3.3"
version = ".jar"

[[modlist]]
name = "create_recycle_0.9.0_forge_1.16.5"
version = ".jar"

[[modlist]]
name = "CreativeCore_v2.2.1_mc1.16.5"
version = ".jar"

[[modlist]]
name = "curios-forge-1.16.5-4.1.0.0"
version = ".jar"

[[modlist]]
name = "DungeonCrawl-1.16.5-2.3.12"
version = ".jar"

[[modlist]]
name = "DungeonsArise-1.16.5-2.1.49-beta"
version = ".jar"

[[modlist]]
name = "Dungeons_Bosses_0.2"
version = ".jar"

[[modlist]]
name = "dungeons_libraries-1.16.5-1.0.6"
version = ".jar"

[[modlist]]
name = "dungeons_mobs-1.16.5-2.2.3"
version = ".jar"

[[modlist]]
name = "DynamicTrees-1.16.5-0.10.5"
version = ".jar"

[[modlist]]
name = "DynamicTreesBOP-1.16.5-2.0.9"
version = ".jar"

[[modlist]]
name = "DynamicTreesTConstruct-1.16.5-1.3.0"
version = ".jar"

[[modlist]]
name = "embeddium-0.2.4+mc1.16.5"
version = ".jar"

[[modlist]]
name = "embeddium-extras-mc1.16.5_v1.10.4"
version = ".jar"

[[modlist]]
name = "embeddiumextension-1.16.5-0.0.6"
version = ".jar"

[[modlist]]
name = "EnchantingInfuser-v1.0.2-1.16.5-Forge"
version = ".jar"

[[modlist]]
name = "entitycollisionfpsfix-1.16-1.0.1"
version = ".jar"

[[modlist]]
name = "EntityCulling-1.16.5-2.1.7"
version = ".jar"

[[modlist]]
name = "fancymenu_forge_2.14.9_MC_1.16.2-1.16.5"
version = ".jar"

[[modlist]]
name = "FarmersDelight-1.16.5-0.6.0"
version = ".jar"

[[modlist]]
name = "FasterLadderClimbing-1.16.4-0.2.1"
version = ".jar"

[[modlist]]
name = "FastLeafDecay-v25.2"
version = ".jar"

[[modlist]]
name = "FastSuite-1.16.4-1.1.1"
version = ".jar"

[[modlist]]
name = "ferritecore-2.1.1-forge"
version = ".jar"

[[modlist]]
name = "flywheel-1.16-0.2.5"
version = ".jar"

[[modlist]]
name = "forgedfabric-0.0.7+1.16"
version = ".jar"

[[modlist]]
name = "FpsReducer-forge-1.24-mc1.16.5"
version = ".jar"

[[modlist]]
name = "geckolib-forge-1.16.5-3.0.106"
version = ".jar"

[[modlist]]
name = "getittogetherdrops-1.16.5-v1.2"
version = ".jar"

[[modlist]]
name = "Goblins_Dungeons_1.0.6-1.16"
version = ".jar"

[[modlist]]
name = "goblintraders-1.7.3-1.16.5"
version = ".jar"

[[modlist]]
name = "GokiStats-1.16.5-1.3.2"
version = ".jar"

[[modlist]]
name = "gravestone-1.16.5-1.0.6"
version = ".jar"

[[modlist]]
name = "HardcoreRevival_1.16.5-5.2.1"
version = ".jar"

[[modlist]]
name = "iceandfire-2.1.12-1.16.5-patch-1"
version = ".jar"

[[modlist]]
name = "immersive-armors-1.5.1+1.16.5-forge"
version = ".jar"

[[modlist]]
name = "immersive_aircraft-0.5.2+1.16.5-forge"
version = ".jar"

[[modlist]]
name = "ImprovedBackpacks-1.6.2.1"
version = ".jar"

[[modlist]]
name = "inventorysorter-1.16.1-18.1.0"
version = ".jar"

[[modlist]]
name = "Jade-1.16.4-2.8.3"
version = ".jar"

[[modlist]]
name = "JEITweaker-1.16.5-1.1.0.49"
version = ".jar"

[[modlist]]
name = "konkrete_forge_1.6.1_MC_1.16.2-1.16.5"
version = ".jar"

[[modlist]]
name = "kotlinforforge-1.17.0-obf"
version = ".jar"

[[modlist]]
name = "kryptonreforged-mc1.16.5_v1.0.0"
version = ".jar"

[[modlist]]
name = "Ksyxis-Forge1.14thru1.16-1.1"
version = ".jar"

[[modlist]]
name = "kubejs-create-1605.1.4-build.12"
version = ".jar"

[[modlist]]
name = "kubejs-forge-1605.3.19-build.299"
version = ".jar"

[[modlist]]
name = "lazydfu-0.1.3"
version = ".jar"

[[modlist]]
name = "majrusz-library-1.16.4-2.0.1"
version = ".jar"

[[modlist]]
name = "majruszs-difficulty-1.16.4-1.1.0"
version = ".jar"

[[modlist]]
name = "Mantle-1.16.5-1.6.157"
version = ".jar"

[[modlist]]
name = "mcw-furniture-3.2.0-mc1.16.5forge"
version = ".jar"

[[modlist]]
name = "minecraft-comes-alive-7.3.23+1.16.5-universal"
version = ".jar"

[[modlist]]
name = "mobifier-1.1.4"
version = ".jar"

[[modlist]]
name = "morecfm-1.3.1-1.16.3"
version = ".jar"

[[modlist]]
name = "morecreatestuffs-mc1.16-1.4.1b"
version = ".jar"

[[modlist]]
name = "Morpheus-1.16.5-4.2.70"
version = ".jar"

[[modlist]]
name = "mowziesmobs-1.5.27"
version = ".jar"

[[modlist]]
name = "MutantBeasts-1.16.4-1.1.3"
version = ".jar"

[[modlist]]
name = "obscure_api-11"
version = ".jar"

[[modlist]]
name = "occultism-1.16.5-1.29.1"
version = ".jar"

[[modlist]]
name = "out_of_sight-1.16.4-1.0.1"
version = ".jar"

[[modlist]]
name = "overworld_two-1.1-1.16.5"
version = ".jar"

[[modlist]]
name = "passiveshield_1.16.5-2.6"
version = ".jar"

[[modlist]]
name = "Patchouli-1.16.4-53.3"
version = ".jar"

[[modlist]]
name = "Placebo-1.16.5-4.7.1"
version = ".jar"

[[modlist]]
name = "player-animation-lib-forge-0.3.5+1.16.5"
version = ".jar"

[[modlist]]
name = "PuzzlesLib-v1.0.15-1.16.5-Forge"
version = ".jar"

[[modlist]]
name = "reap-1.16.5-1.0.1"
version = ".jar"

[[modlist]]
name = "rhino-forge-1605.1.5-build.75"
version = ".jar"

[[modlist]]
name = "RoadRunner-mc1.16.5-1.4.1"
version = ".jar"

[[modlist]]
name = "RoughlyEnoughItems-6.5.436"
version = ".jar"

[[modlist]]
name = "shutupexperimentalsettings-1.0.3"
version = ".jar"

[[modlist]]
name = "smoothboot-forge-1.16.4-1.2.2"
version = ".jar"

[[modlist]]
name = "spark-1.9.1-forge"
version = ".jar"

[[modlist]]
name = "SpawnerFix-1.16.2-1.0.0.2"
version = ".jar"

[[modlist]]
name = "spoornextras-1.0"
version = ".jar"

[[modlist]]
name = "stalwart-dungeons-1.16.5-1.1.7"
version = ".jar"

[[modlist]]
name = "starlight-1.2"
version = ".jar"

[[modlist]]
name = "strawgolem-1.16-1.9"
version = ".jar"

[[modlist]]
name = "TConstruct-1.16.5-3.3.4.335"
version = ".jar"

[[modlist]]
name = "TerraForged-1.16.5-0.2.16"
version = ".jar"

[[modlist]]
name = "theurgy-1.16.5-1.0.8"
version = ".jar"

[[modlist]]
name = "TrashSlot_1.16.3-12.2.1"
version = ".jar"

[[modlist]]
name = "twilightforest"
version = ".jar"

[[modlist]]
name = "upgrade_aquatic-1.16.5-3.1.2"
version = ".jar"

[[modlist]]
name = "useless-sword-1.16.5-V1.3.7"
version = ".jar"

[[modlist]]
name = "voicechat-forge-1.16.5-2.4.27"
version = ".jar"

[[modlist]]
name = "Xaeros_Minimap_FP23.8.2_Forge_1.16.5"
version = ".jar"

[[modlist]]
name = "xlpackets-1.16.4-1.2"
version = ".jar"

[[modlist]]
name = "YungsApi-1.16.4-Forge-13"
version = ".jar"

[[modlist]]
name = "YungsBridges-Forge-1.16.4-1.0.1"
version = ".jar"

[[modlist]]
name = "YungsExtras-Forge-1.16.4-1.0"
version = ".jar"

[[modlist]]
name = "[1.16.5]SecurityCraftv1.9.8"
version = ".jar"

[[modlist]]
name = "[1.16.5][Forge]RPG-HUD-3.9.1"
version = ".jar"

